# fly.toml app configuration file generated for darryltest on 2023-09-30T12:17:56+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brokenhillmines"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[build]

[env]
  DB_CLIENT = "pg"
  DB_HOST=ep-lingering-night-a7kb8r46.ap-southeast-2.aws.neon.tech
  DB_PORT=5432
  DB_DATABASE=navarch_db
  DB_USER=admin
  DB_PASSWORD=Ff3HPpEog7ad
  DB_SSL=true
  FLY_PRIMARY_REGION = "syd"
  PORT = "8055"

[[mounts]]
  source = "data"
  destination = "/mnt/data"

[[services]]
  protocol = "tcp"
  internal_port = 8055
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/server/health"
    protocol = "http"
    tls_skip_verify = false
