# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    strategy:
      matrix:
        instance: ["navarch", "navarch-11", "brokenhillmines"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set APP_NAME
        run: echo "APP_NAME=${{ matrix.instance }}" >> $GITHUB_ENV
      - name: Source environment variables
        run: |
          ./deploy.sh ${{ matrix.instance }}
